const actionTypes = Object.freeze({
    PROCESS_ACTION: "PROCESS_ACTION",
    PROCESS_ACTION_FAILED: "PROCESS_ACTION_FAILED",
    UPDATE_TOKEN: "UPDATE_TOKEN",

    PROCESS_MESSAGE_ACTION: "PROCESS_MESSAGE_ACTION",
    PROCESS_MESSAGE_ACTION_FAILED: "PROCESS_MESSAGE_ACTION_FAILED",
    CONVERSATIONS_LOADED: "CONVERSATIONS_LOADED",
    MESSAGES_REQUESTED: "MESSAGES_REQUESTED",
    NEW_MESSAGE_ADDED: "NEW_MESSAGE_ADDED",

    CHANGE_LAST_MESSAGE: "CHANGE_LAST_MESSAGE"
})
export default actionTypes